import { withBunCompressionHeaders } from "../../../bun.js";
import { fetchWithTimeout } from "../../../link-preview/fetch-with-timeout.js";
import { parseTimestampToMs } from "../../timestamps.js";
import { decodeHtmlEntities, sanitizeYoutubeJsonResponse } from "../../utils.js";
import { extractYoutubeiBootstrap } from "./api.js";
import {
  CaptionEventRecord,
  CaptionListRenderer,
  CaptionPayload,
  CaptionSegmentRecord,
  CaptionTrackRecord,
  CaptionsPayload,
  REQUEST_HEADERS,
  TranscriptPayload,
  YoutubePlayerContext,
  YoutubeTranscriptContext,
  isObjectLike,
} from "./captions-shared.js";
import { extractInitialPlayerResponse, extractInnertubeApiKey } from "./captions-player.js";

async function fetchTranscriptViaAndroidPlayer(
  fetchImpl: typeof fetch,
  {
    html,
    videoId,
    skipAutoGenerated,
  }: { html: string; videoId: string; skipAutoGenerated?: boolean },
): Promise<TranscriptPayload | null> {
  const apiKey = extractInnertubeApiKey(html);
  if (!apiKey) {
    return null;
  }

  try {
    const userAgent =
      REQUEST_HEADERS["User-Agent"] ??
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36";

    const response = await fetchWithTimeout(
      fetchImpl,
      `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
      {
        method: "POST",
        headers: withBunCompressionHeaders({
          "Content-Type": "application/json",
          "User-Agent": userAgent,
          "Accept-Language": REQUEST_HEADERS["Accept-Language"] ?? "en-US,en;q=0.9",
          Accept: "application/json",
        }),
        body: JSON.stringify({
          context: {
            client: {
              clientName: "ANDROID",
              clientVersion: "20.10.38",
            },
          },
          videoId,
        }),
      },
    );

    if (!response.ok) {
      return null;
    }

    const parsed: unknown = await response.json();
    if (!isObjectLike(parsed)) {
      return null;
    }

    return await extractTranscriptFromPlayerPayload(fetchImpl, parsed, skipAutoGenerated);
  } catch {
    return null;
  }
}

export const fetchTranscriptFromCaptionTracks = async (
  fetchImpl: typeof fetch,
  {
    html,
    originalUrl,
    videoId,
    skipAutoGenerated,
  }: YoutubeTranscriptContext & { skipAutoGenerated?: boolean },
): Promise<TranscriptPayload | null> => {
  const initialPlayerResponse = extractInitialPlayerResponse(html);
  if (initialPlayerResponse) {
    const transcript = await extractTranscriptFromPlayerPayload(
      fetchImpl,
      initialPlayerResponse,
      skipAutoGenerated,
    );
    if (transcript) {
      return transcript;
    }
  }

  const bootstrap = extractYoutubeiBootstrap(html);
  if (!bootstrap) {
    return await fetchTranscriptViaAndroidPlayer(fetchImpl, { html, videoId, skipAutoGenerated });
  }

  const { apiKey, clientName, clientVersion, context, pageCl, pageLabel, visitorData, xsrfToken } =
    bootstrap;
  if (!apiKey) {
    return await fetchTranscriptViaAndroidPlayer(fetchImpl, { html, videoId, skipAutoGenerated });
  }

  const contextRecord = context as YoutubePlayerContext;
  const clientContext = isObjectLike(contextRecord.client)
    ? (contextRecord.client as Record<string, unknown>)
    : {};
  const requestBody: Record<string, unknown> = {
    context: {
      ...contextRecord,
      client: {
        ...clientContext,
        originalUrl,
      },
    },
    videoId,
    playbackContext: {
      contentPlaybackContext: {
        html5Preference: "HTML5_PREF_WANTS",
      },
    },
    contentCheckOk: true,
    racyCheckOk: true,
  };

  try {
    const userAgent =
      REQUEST_HEADERS["User-Agent"] ??
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36";
    const headers: Record<string, string> = withBunCompressionHeaders({
      "Content-Type": "application/json",
      "User-Agent": userAgent,
      Accept: "application/json",
      Origin: "https://www.youtube.com",
      Referer: originalUrl,
      "X-Goog-AuthUser": "0",
      "X-Youtube-Bootstrap-Logged-In": "false",
    });

    if (clientName) headers["X-Youtube-Client-Name"] = clientName;
    if (clientVersion) headers["X-Youtube-Client-Version"] = clientVersion;
    if (visitorData) headers["X-Goog-Visitor-Id"] = visitorData;
    if (typeof pageCl === "number" && Number.isFinite(pageCl)) {
      headers["X-Youtube-Page-CL"] = String(pageCl);
    }
    if (pageLabel) headers["X-Youtube-Page-Label"] = pageLabel;
    if (xsrfToken) headers["X-Youtube-Identity-Token"] = xsrfToken;

    const response = await fetchWithTimeout(
      fetchImpl,
      `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
      {
        method: "POST",
        headers,
        body: JSON.stringify(requestBody),
      },
    );

    if (!response.ok) {
      return await fetchTranscriptViaAndroidPlayer(fetchImpl, { html, videoId, skipAutoGenerated });
    }

    const raw = await response.text();
    const sanitized = sanitizeYoutubeJsonResponse(raw);
    const parsed: unknown = JSON.parse(sanitized);
    if (!isObjectLike(parsed)) {
      return await fetchTranscriptViaAndroidPlayer(fetchImpl, { html, videoId, skipAutoGenerated });
    }

    const transcript = await extractTranscriptFromPlayerPayload(
      fetchImpl,
      parsed,
      skipAutoGenerated,
    );
    if (transcript) {
      return transcript;
    }

    return await fetchTranscriptViaAndroidPlayer(fetchImpl, { html, videoId, skipAutoGenerated });
  } catch {
    return await fetchTranscriptViaAndroidPlayer(fetchImpl, { html, videoId, skipAutoGenerated });
  }
};

const extractTranscriptFromPlayerPayload = async (
  fetchImpl: typeof fetch,
  payload: Record<string, unknown>,
  skipAutoGenerated?: boolean,
): Promise<TranscriptPayload | null> => {
  const payloadRecord = payload as CaptionsPayload;

  const captionsCandidate = payloadRecord.captions;
  const captions = isObjectLike(captionsCandidate) ? (captionsCandidate as CaptionsPayload) : null;

  const rendererCandidate =
    (captions ? (captions as CaptionsPayload).playerCaptionsTracklistRenderer : null) ??
    payloadRecord.playerCaptionsTracklistRenderer;

  const renderer = isObjectLike(rendererCandidate)
    ? (rendererCandidate as CaptionListRenderer)
    : null;
  const captionTracks = Array.isArray(renderer?.captionTracks)
    ? (renderer?.captionTracks as unknown[])
    : null;
  const automaticTracks = Array.isArray(renderer?.automaticCaptions)
    ? (renderer?.automaticCaptions as unknown[])
    : null;

  const orderedTracks: Record<string, unknown>[] = [];
  if (captionTracks) {
    orderedTracks.push(
      ...captionTracks.filter((track): track is Record<string, unknown> => isObjectLike(track)),
    );
  }
  if (!skipAutoGenerated && automaticTracks) {
    orderedTracks.push(
      ...automaticTracks.filter((track): track is Record<string, unknown> => isObjectLike(track)),
    );
  }

  const sortedTracks = [...orderedTracks].toSorted((a, b) => {
    const aTrack = a as CaptionTrackRecord;
    const bTrack = b as CaptionTrackRecord;
    const aKind = typeof aTrack.kind === "string" ? aTrack.kind : "";
    const bKind = typeof bTrack.kind === "string" ? bTrack.kind : "";
    if (aKind === "asr" && bKind !== "asr") return 1;
    if (bKind === "asr" && aKind !== "asr") return -1;
    const aLang = typeof aTrack.languageCode === "string" ? aTrack.languageCode : "";
    const bLang = typeof bTrack.languageCode === "string" ? bTrack.languageCode : "";
    const aIsEnglish = aLang === "en" || aLang.startsWith("en-");
    const bIsEnglish = bLang === "en" || bLang.startsWith("en-");
    if (aIsEnglish && !bIsEnglish) return -1;
    if (bIsEnglish && !aIsEnglish) return 1;
    return 0;
  });

  const seenLanguages = new Set<string>();
  const normalizedTracks: Record<string, unknown>[] = [];
  for (const candidate of sortedTracks) {
    const trackRecord = candidate as CaptionTrackRecord;
    const languageCandidate = trackRecord.languageCode;
    const lang = typeof languageCandidate === "string" ? languageCandidate.toLowerCase() : "";
    if (lang && seenLanguages.has(lang)) {
      continue;
    }
    if (lang) {
      seenLanguages.add(lang);
    }
    normalizedTracks.push(candidate);
  }

  const tracksToUse = skipAutoGenerated
    ? normalizedTracks.filter((track) => {
        const t = track as CaptionTrackRecord;
        return t.kind !== "asr";
      })
    : normalizedTracks;

  if (tracksToUse.length === 0) {
    return null;
  }

  return await findFirstTranscript(fetchImpl, tracksToUse, 0);
};

const findFirstTranscript = async (
  fetchImpl: typeof fetch,
  tracks: readonly Record<string, unknown>[],
  index: number,
): Promise<TranscriptPayload | null> => {
  if (index >= tracks.length) {
    return null;
  }
  const candidate = await downloadCaptionTrack(fetchImpl, tracks[index] ?? {});
  if (candidate) {
    return candidate;
  }
  return findFirstTranscript(fetchImpl, tracks, index + 1);
};

const downloadCaptionTrack = async (
  fetchImpl: typeof fetch,
  track: Record<string, unknown>,
): Promise<TranscriptPayload | null> => {
  const trackRecord = track as CaptionTrackRecord;
  const baseUrl =
    typeof trackRecord.baseUrl === "string"
      ? trackRecord.baseUrl
      : typeof trackRecord.url === "string"
        ? trackRecord.url
        : null;
  if (!baseUrl) {
    return null;
  }

  const json3Url = (() => {
    try {
      const parsed = new URL(baseUrl);
      parsed.searchParams.set("fmt", "json3");
      parsed.searchParams.set("alt", "json");
      return parsed.toString();
    } catch {
      const separator = baseUrl.includes("?") ? "&" : "?";
      return `${baseUrl}${separator}fmt=json3&alt=json`;
    }
  })();

  try {
    const response = await fetchWithTimeout(fetchImpl, json3Url, {
      headers: REQUEST_HEADERS,
    });
    if (!response.ok) {
      return await downloadXmlTranscript(fetchImpl, baseUrl);
    }

    const text = await response.text();
    if (text.length === 0) {
      return await downloadXmlTranscript(fetchImpl, baseUrl);
    }
    const jsonResult = parseJsonTranscript(text);
    if (jsonResult) return jsonResult;
    const xmlFallback = parseXmlTranscript(text);
    if (xmlFallback) return xmlFallback;
    return await downloadXmlTranscript(fetchImpl, baseUrl);
  } catch {
    return await downloadXmlTranscript(fetchImpl, baseUrl);
  }
};

const downloadXmlTranscript = async (
  fetchImpl: typeof fetch,
  baseUrl: string,
): Promise<TranscriptPayload | null> => {
  const xmlUrl = baseUrl.replaceAll(/&fmt=[^&]+/g, "");
  try {
    const response = await fetchWithTimeout(fetchImpl, xmlUrl, { headers: REQUEST_HEADERS });
    if (!response.ok) {
      return null;
    }
    const text = await response.text();
    const jsonResult = parseJsonTranscript(text);
    if (jsonResult) {
      return jsonResult;
    }
    return parseXmlTranscript(text);
  } catch {
    return null;
  }
};

const parseJsonTranscript = (raw: string): TranscriptPayload | null => {
  try {
    const parsed: unknown = JSON.parse(raw);
    if (!isObjectLike(parsed)) {
      return null;
    }
    const payloadRecord = parsed as CaptionPayload;
    const eventsUnknown = payloadRecord.events;
    if (!Array.isArray(eventsUnknown)) {
      return null;
    }
    const lines: string[] = [];
    const segments = [];
    for (const event of eventsUnknown) {
      if (!isObjectLike(event)) continue;
      const eventRecord = event as CaptionEventRecord;
      const segs = Array.isArray(eventRecord.segs) ? (eventRecord.segs as unknown[]) : null;
      if (!segs) continue;
      const text = segs
        .map((seg) => {
          if (!isObjectLike(seg)) return "";
          const segRecord = seg as CaptionSegmentRecord;
          return typeof segRecord.utf8 === "string" ? segRecord.utf8 : "";
        })
        .join("")
        .trim();
      if (text.length > 0) {
        lines.push(text);
        const startMs = parseTimestampToMs(eventRecord.tStartMs, false);
        const durationMs = parseTimestampToMs(eventRecord.dDurationMs, false);
        if (startMs != null) {
          segments.push({
            startMs,
            endMs: durationMs != null ? startMs + durationMs : null,
            text: text.replace(/\s+/g, " ").trim(),
          });
        }
      }
    }
    const transcript = lines.join("\n").trim();
    if (transcript.length === 0) {
      return null;
    }
    return {
      text: transcript,
      segments: segments.length > 0 ? segments : null,
    };
  } catch {
    return null;
  }
};

const parseXmlTranscript = (xml: string): TranscriptPayload | null => {
  const pattern = /<text[^>]*>([\s\S]*?)<\/text>/gi;
  const lines: string[] = [];
  const segments = [];
  let match: RegExpExecArray | null = pattern.exec(xml);
  while (match) {
    const content = match[1] ?? "";
    const decoded = decodeHtmlEntities(content).replaceAll(/\s+/g, " ").trim();
    if (decoded.length > 0) {
      lines.push(decoded);
      const tag = match[0] ?? "";
      const startMatch = tag.match(/\bstart\s*=\s*(['"])([^'"]+)\1/i);
      const durMatch = tag.match(/\bdur\s*=\s*(['"])([^'"]+)\1/i);
      const startMs = startMatch?.[2] ? parseTimestampToMs(startMatch[2], true) : null;
      const durationMs = durMatch?.[2] ? parseTimestampToMs(durMatch[2], true) : null;
      if (startMs != null) {
        segments.push({
          startMs,
          endMs: durationMs != null ? startMs + durationMs : null,
          text: decoded.replace(/\s+/g, " ").trim(),
        });
      }
    }
    match = pattern.exec(xml);
  }
  const transcript = lines.join("\n").trim();
  if (transcript.length === 0) {
    return null;
  }
  return {
    text: transcript,
    segments: segments.length > 0 ? segments : null,
  };
};
