import type { TranscriptionConfig } from "../../transcription-config.js";
import type {
  ProviderContext,
  ProviderFetchOptions,
  ProviderResult,
  TranscriptSource,
} from "../../types.js";
import { normalizeTranscriptText } from "../../normalize.js";
import { extractYouTubeVideoId } from "../../utils.js";
import { extractYoutubeiTranscriptConfig, fetchTranscriptFromTranscriptEndpoint } from "./api.js";
import { fetchTranscriptWithApify } from "./apify.js";
import {
  extractYoutubeDurationSeconds,
  fetchTranscriptFromCaptionTracks,
  fetchYoutubeDurationSecondsViaPlayer,
} from "./captions.js";
import { fetchDurationSecondsWithYtDlp, fetchTranscriptWithYtDlp } from "./yt-dlp.js";

const YOUTUBE_BOOTSTRAP_PATTERN = /ytcfg\.set|ytInitialPlayerResponse/;
const WATCH_PAGE_HEADERS = {
  "User-Agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36",
  Accept: "text/html,application/xhtml+xml",
};

type DurationMetadata = { durationSeconds: number } | null;

export type YouTubeProviderFlow = {
  context: ProviderContext;
  options: ProviderFetchOptions;
  transcription: TranscriptionConfig;
  htmlText: string;
  attemptedProviders: TranscriptSource[];
  notes: string[];
  effectiveVideoId: string | null;
  durationMetadata: DurationMetadata;
  canRunYtDlp: boolean;
  pushHint: (hint: string) => void;
};

export async function loadYoutubeHtml(
  context: ProviderContext,
  options: ProviderFetchOptions,
): Promise<string | null> {
  const { html: initialHtml, url } = context;
  if (typeof initialHtml === "string" && YOUTUBE_BOOTSTRAP_PATTERN.test(initialHtml)) {
    return initialHtml;
  }

  try {
    const response = await options.fetch(url, { headers: WATCH_PAGE_HEADERS });
    if (response.ok) return await response.text();
  } catch {
    // Ignore and fall back to the caller-provided HTML.
  }

  return initialHtml;
}

export function resolveEffectiveVideoId(context: ProviderContext): string | null {
  const candidate = context.resourceKey ?? extractYouTubeVideoId(context.url);
  return typeof candidate === "string" && candidate.trim().length > 0 ? candidate.trim() : null;
}

export async function resolveDurationMetadata(args: {
  htmlText: string;
  effectiveVideoId: string | null;
  url: string;
  options: ProviderFetchOptions;
}): Promise<DurationMetadata> {
  const { htmlText, effectiveVideoId, url, options } = args;

  let durationSeconds = extractYoutubeDurationSeconds(htmlText);
  if (!durationSeconds && effectiveVideoId) {
    durationSeconds = await fetchYoutubeDurationSecondsViaPlayer(options.fetch, {
      html: htmlText,
      videoId: effectiveVideoId,
    });
  }
  if (!durationSeconds && options.ytDlpPath) {
    durationSeconds = await fetchDurationSecondsWithYtDlp({
      ytDlpPath: options.ytDlpPath,
      url,
    });
  }

  return typeof durationSeconds === "number" &&
    Number.isFinite(durationSeconds) &&
    durationSeconds > 0
    ? { durationSeconds }
    : null;
}

export async function tryApifyTranscript(
  flow: YouTubeProviderFlow,
  hint: string,
): Promise<ProviderResult | null> {
  if (!flow.options.apifyApiToken) return null;

  flow.pushHint(hint);
  flow.attemptedProviders.push("apify");

  const transcript = await fetchTranscriptWithApify(
    flow.options.fetch,
    flow.options.apifyApiToken,
    flow.context.url,
  );
  if (!transcript) return null;

  return {
    text: normalizeTranscriptText(transcript),
    source: "apify",
    metadata: { provider: "apify", ...(flow.durationMetadata ?? {}) },
    attemptedProviders: flow.attemptedProviders,
  };
}

export async function tryManualCaptionTranscript(
  flow: YouTubeProviderFlow,
): Promise<ProviderResult | null> {
  if (!flow.effectiveVideoId) {
    return { text: null, source: null, attemptedProviders: flow.attemptedProviders };
  }

  flow.pushHint("YouTube: checking creator captions only (skipping auto-generated)");
  flow.attemptedProviders.push("captionTracks");

  const transcript = await fetchTranscriptFromCaptionTracks(flow.options.fetch, {
    html: flow.htmlText,
    originalUrl: flow.context.url,
    videoId: flow.effectiveVideoId,
    skipAutoGenerated: true,
  });
  if (!transcript?.text) return null;

  return {
    text: normalizeTranscriptText(transcript.text),
    source: "captionTracks",
    segments: flow.options.transcriptTimestamps ? (transcript.segments ?? null) : null,
    metadata: { provider: "captionTracks", manualOnly: true, ...(flow.durationMetadata ?? {}) },
    attemptedProviders: flow.attemptedProviders,
  };
}

export async function tryWebTranscript(flow: YouTubeProviderFlow): Promise<ProviderResult | null> {
  if (!flow.effectiveVideoId) {
    return { text: null, source: null, attemptedProviders: flow.attemptedProviders };
  }

  flow.pushHint("YouTube: checking captions (youtubei)");
  const config = extractYoutubeiTranscriptConfig(flow.htmlText);
  if (config) {
    flow.attemptedProviders.push("youtubei");
    const transcript = await fetchTranscriptFromTranscriptEndpoint(flow.options.fetch, {
      config,
      originalUrl: flow.context.url,
    });
    if (transcript?.text) {
      return {
        text: normalizeTranscriptText(transcript.text),
        source: "youtubei",
        segments: flow.options.transcriptTimestamps ? (transcript.segments ?? null) : null,
        metadata: { provider: "youtubei", ...(flow.durationMetadata ?? {}) },
        attemptedProviders: flow.attemptedProviders,
      };
    }
  }

  flow.pushHint(
    config
      ? "YouTube: youtubei empty; checking caption tracks"
      : "YouTube: youtubei unavailable; checking caption tracks",
  );
  flow.attemptedProviders.push("captionTracks");

  const transcript = await fetchTranscriptFromCaptionTracks(flow.options.fetch, {
    html: flow.htmlText,
    originalUrl: flow.context.url,
    videoId: flow.effectiveVideoId,
  });
  if (!transcript?.text) return null;

  return {
    text: normalizeTranscriptText(transcript.text),
    source: "captionTracks",
    segments: flow.options.transcriptTimestamps ? (transcript.segments ?? null) : null,
    metadata: { provider: "captionTracks", ...(flow.durationMetadata ?? {}) },
    attemptedProviders: flow.attemptedProviders,
  };
}

export async function tryYtDlpTranscript(args: {
  flow: YouTubeProviderFlow;
  mode: ProviderFetchOptions["youtubeTranscriptMode"];
}): Promise<ProviderResult | null> {
  const { flow, mode } = args;

  if (mode === "no-auto" && !flow.canRunYtDlp) {
    throw new Error(
      "--youtube no-auto requires yt-dlp and a transcription provider (whisper-cpp, GROQ_API_KEY, ASSEMBLYAI_API_KEY, GEMINI_API_KEY, OPENAI_API_KEY, or FAL_KEY) for fallback",
    );
  }

  if (mode === "auto") {
    flow.pushHint("YouTube: captions unavailable; falling back to yt-dlp audio");
  } else if (mode === "no-auto") {
    flow.pushHint("YouTube: no creator captions; falling back to yt-dlp audio");
  } else {
    flow.pushHint("YouTube: downloading audio (yt-dlp)");
  }

  flow.attemptedProviders.push("yt-dlp");
  const ytdlpResult = await fetchTranscriptWithYtDlp({
    ytDlpPath: flow.options.ytDlpPath,
    transcription: flow.transcription,
    mediaCache: flow.options.mediaCache ?? null,
    url: flow.context.url,
    onProgress: flow.options.onProgress ?? null,
    mediaKind: "video",
  });
  if (ytdlpResult.notes.length > 0) flow.notes.push(...ytdlpResult.notes);

  if (ytdlpResult.text) {
    return {
      text: normalizeTranscriptText(ytdlpResult.text),
      source: "yt-dlp",
      metadata: {
        provider: "yt-dlp",
        transcriptionProvider: ytdlpResult.provider,
        ...(flow.durationMetadata ?? {}),
      },
      attemptedProviders: flow.attemptedProviders,
      notes: joinNotes(flow.notes),
    };
  }

  if (mode === "yt-dlp" && ytdlpResult.error) throw ytdlpResult.error;
  return null;
}

export function buildUnavailableResult(flow: YouTubeProviderFlow): ProviderResult {
  flow.attemptedProviders.push("unavailable");
  return {
    text: null,
    source: "unavailable",
    metadata: {
      provider: "youtube",
      reason: "no_transcript_available",
      ...(flow.durationMetadata ?? {}),
    },
    attemptedProviders: flow.attemptedProviders,
    notes: joinNotes(flow.notes),
  };
}

function joinNotes(notes: string[]): string | null {
  return notes.length > 0 ? notes.join("; ") : null;
}
